Update bins

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -1,11 +1,31 @@
 #!/bin/bash
 
+while getopts "q" OPTION
+do
+  case $OPTION in
+    q)
+      QUIET=true
+      ;;
+  esac
+done
+
 result=0
 
 bin=$(dirname $0)
 
+# Travis randomly kills go builds when using -race
+race=$([ "$TRAVIS" != "true" ] && echo "-race")
+
 echo -e "\n Formatting packages..."
 $bin/go fmt ./...
+let "result+=$?"
+
+echo -e "\n Vetting packages for potential issues..."
+$bin/go vet ./...
+let "result+=$?"
+
+echo -e "\n Checking with golint..."
+$bin/golint
 let "result+=$?"
 
 echo -e "\n Installing ginkgo..."
@@ -13,21 +33,19 @@ $bin/go install github.com/onsi/ginkgo/ginkgo
 let "result+=$?"
 
 echo -e "\n Testing packages..."
-$bin/env ginkgo -r $bin/..
-let "result+=$?"
-
-echo -e "\n Vetting packages for potential issues..."
-$bin/go vet ./...
+$bin/env ginkgo -r $race $bin/..
 let "result+=$?"
 
 echo -e "\n Running build script to confirm everything compiles..."
 $bin/build
 let "result+=$?"
 
-if [ $result -eq 0 ]; then
-	echo -e "\nSUITE SUCCESS"
-else
-	echo -e "\nSUITE FAILURE"
+if [ ! $QUIET ]; then
+  if [ $result -eq 0 ]; then
+    echo -e "\n\033[0;32mSUITE SUCCESS\033[0m"
+  else
+    echo -e "\n\033[0;31mSUITE FAILURE (exit code: $result)\033[0m"
+  fi
 fi
 
 exit $result
